/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedKomersialEmailRouteImport } from './routes/_protected/komersial/email'
import { Route as ProtectedKomersialPenawaranIndexRouteImport } from './routes/_protected/komersial/penawaran/index'
import { Route as ProtectedKomersialPenawaranIdRouteImport } from './routes/_protected/komersial/penawaran/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedKomersialEmailRoute = ProtectedKomersialEmailRouteImport.update({
  id: '/komersial/email',
  path: '/komersial/email',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedKomersialPenawaranIndexRoute =
  ProtectedKomersialPenawaranIndexRouteImport.update({
    id: '/komersial/penawaran/',
    path: '/komersial/penawaran/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKomersialPenawaranIdRoute =
  ProtectedKomersialPenawaranIdRouteImport.update({
    id: '/komersial/penawaran/$id',
    path: '/komersial/penawaran/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/komersial/email': typeof ProtectedKomersialEmailRoute
  '/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/komersial/penawaran/': typeof ProtectedKomersialPenawaranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/komersial/email': typeof ProtectedKomersialEmailRoute
  '/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/komersial/penawaran': typeof ProtectedKomersialPenawaranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/komersial/email': typeof ProtectedKomersialEmailRoute
  '/_protected/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/_protected/komersial/penawaran/': typeof ProtectedKomersialPenawaranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/login'
    | '/dashboard'
    | '/komersial/email'
    | '/komersial/penawaran/$id'
    | '/komersial/penawaran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/login'
    | '/dashboard'
    | '/komersial/email'
    | '/komersial/penawaran/$id'
    | '/komersial/penawaran'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/home'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/komersial/email'
    | '/_protected/komersial/penawaran/$id'
    | '/_protected/komersial/penawaran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/email': {
      id: '/_protected/komersial/email'
      path: '/komersial/email'
      fullPath: '/komersial/email'
      preLoaderRoute: typeof ProtectedKomersialEmailRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/penawaran/': {
      id: '/_protected/komersial/penawaran/'
      path: '/komersial/penawaran'
      fullPath: '/komersial/penawaran/'
      preLoaderRoute: typeof ProtectedKomersialPenawaranIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/penawaran/$id': {
      id: '/_protected/komersial/penawaran/$id'
      path: '/komersial/penawaran/$id'
      fullPath: '/komersial/penawaran/$id'
      preLoaderRoute: typeof ProtectedKomersialPenawaranIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedKomersialEmailRoute: typeof ProtectedKomersialEmailRoute
  ProtectedKomersialPenawaranIdRoute: typeof ProtectedKomersialPenawaranIdRoute
  ProtectedKomersialPenawaranIndexRoute: typeof ProtectedKomersialPenawaranIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedKomersialEmailRoute: ProtectedKomersialEmailRoute,
  ProtectedKomersialPenawaranIdRoute: ProtectedKomersialPenawaranIdRoute,
  ProtectedKomersialPenawaranIndexRoute: ProtectedKomersialPenawaranIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
