/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedKomersialEmailRouteImport } from './routes/_protected/komersial/email'
import { Route as ProtectedOprasionalPembayaranIndexRouteImport } from './routes/_protected/oprasional/pembayaran/index'
import { Route as ProtectedOprasionalOprasionalIndexRouteImport } from './routes/_protected/oprasional/oprasional/index'
import { Route as ProtectedOprasionalCasbonIndexRouteImport } from './routes/_protected/oprasional/casbon/index'
import { Route as ProtectedKomersialPenawaranIndexRouteImport } from './routes/_protected/komersial/penawaran/index'
import { Route as ProtectedKeuanganExpenseIndexRouteImport } from './routes/_protected/keuangan/expense/index'
import { Route as ProtectedOprasionalPembayaranIdRouteImport } from './routes/_protected/oprasional/pembayaran/$id'
import { Route as ProtectedOprasionalOprasionalIdRouteImport } from './routes/_protected/oprasional/oprasional/$id'
import { Route as ProtectedOprasionalCasbonCreateRouteImport } from './routes/_protected/oprasional/casbon/create'
import { Route as ProtectedOprasionalCasbonIdRouteImport } from './routes/_protected/oprasional/casbon/$id'
import { Route as ProtectedKomersialPenawaranIdRouteImport } from './routes/_protected/komersial/penawaran/$id'
import { Route as ProtectedKeuanganExpenseIdRouteImport } from './routes/_protected/keuangan/expense/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedKomersialEmailRoute = ProtectedKomersialEmailRouteImport.update({
  id: '/komersial/email',
  path: '/komersial/email',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOprasionalPembayaranIndexRoute =
  ProtectedOprasionalPembayaranIndexRouteImport.update({
    id: '/oprasional/pembayaran/',
    path: '/oprasional/pembayaran/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalOprasionalIndexRoute =
  ProtectedOprasionalOprasionalIndexRouteImport.update({
    id: '/oprasional/oprasional/',
    path: '/oprasional/oprasional/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalCasbonIndexRoute =
  ProtectedOprasionalCasbonIndexRouteImport.update({
    id: '/oprasional/casbon/',
    path: '/oprasional/casbon/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKomersialPenawaranIndexRoute =
  ProtectedKomersialPenawaranIndexRouteImport.update({
    id: '/komersial/penawaran/',
    path: '/komersial/penawaran/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKeuanganExpenseIndexRoute =
  ProtectedKeuanganExpenseIndexRouteImport.update({
    id: '/keuangan/expense/',
    path: '/keuangan/expense/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalPembayaranIdRoute =
  ProtectedOprasionalPembayaranIdRouteImport.update({
    id: '/oprasional/pembayaran/$id',
    path: '/oprasional/pembayaran/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalOprasionalIdRoute =
  ProtectedOprasionalOprasionalIdRouteImport.update({
    id: '/oprasional/oprasional/$id',
    path: '/oprasional/oprasional/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalCasbonCreateRoute =
  ProtectedOprasionalCasbonCreateRouteImport.update({
    id: '/oprasional/casbon/create',
    path: '/oprasional/casbon/create',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOprasionalCasbonIdRoute =
  ProtectedOprasionalCasbonIdRouteImport.update({
    id: '/oprasional/casbon/$id',
    path: '/oprasional/casbon/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKomersialPenawaranIdRoute =
  ProtectedKomersialPenawaranIdRouteImport.update({
    id: '/komersial/penawaran/$id',
    path: '/komersial/penawaran/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedKeuanganExpenseIdRoute =
  ProtectedKeuanganExpenseIdRouteImport.update({
    id: '/keuangan/expense/$id',
    path: '/keuangan/expense/$id',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/komersial/email': typeof ProtectedKomersialEmailRoute
  '/keuangan/expense/$id': typeof ProtectedKeuanganExpenseIdRoute
  '/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/oprasional/casbon/$id': typeof ProtectedOprasionalCasbonIdRoute
  '/oprasional/casbon/create': typeof ProtectedOprasionalCasbonCreateRoute
  '/oprasional/oprasional/$id': typeof ProtectedOprasionalOprasionalIdRoute
  '/oprasional/pembayaran/$id': typeof ProtectedOprasionalPembayaranIdRoute
  '/keuangan/expense/': typeof ProtectedKeuanganExpenseIndexRoute
  '/komersial/penawaran/': typeof ProtectedKomersialPenawaranIndexRoute
  '/oprasional/casbon/': typeof ProtectedOprasionalCasbonIndexRoute
  '/oprasional/oprasional/': typeof ProtectedOprasionalOprasionalIndexRoute
  '/oprasional/pembayaran/': typeof ProtectedOprasionalPembayaranIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/komersial/email': typeof ProtectedKomersialEmailRoute
  '/keuangan/expense/$id': typeof ProtectedKeuanganExpenseIdRoute
  '/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/oprasional/casbon/$id': typeof ProtectedOprasionalCasbonIdRoute
  '/oprasional/casbon/create': typeof ProtectedOprasionalCasbonCreateRoute
  '/oprasional/oprasional/$id': typeof ProtectedOprasionalOprasionalIdRoute
  '/oprasional/pembayaran/$id': typeof ProtectedOprasionalPembayaranIdRoute
  '/keuangan/expense': typeof ProtectedKeuanganExpenseIndexRoute
  '/komersial/penawaran': typeof ProtectedKomersialPenawaranIndexRoute
  '/oprasional/casbon': typeof ProtectedOprasionalCasbonIndexRoute
  '/oprasional/oprasional': typeof ProtectedOprasionalOprasionalIndexRoute
  '/oprasional/pembayaran': typeof ProtectedOprasionalPembayaranIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/komersial/email': typeof ProtectedKomersialEmailRoute
  '/_protected/keuangan/expense/$id': typeof ProtectedKeuanganExpenseIdRoute
  '/_protected/komersial/penawaran/$id': typeof ProtectedKomersialPenawaranIdRoute
  '/_protected/oprasional/casbon/$id': typeof ProtectedOprasionalCasbonIdRoute
  '/_protected/oprasional/casbon/create': typeof ProtectedOprasionalCasbonCreateRoute
  '/_protected/oprasional/oprasional/$id': typeof ProtectedOprasionalOprasionalIdRoute
  '/_protected/oprasional/pembayaran/$id': typeof ProtectedOprasionalPembayaranIdRoute
  '/_protected/keuangan/expense/': typeof ProtectedKeuanganExpenseIndexRoute
  '/_protected/komersial/penawaran/': typeof ProtectedKomersialPenawaranIndexRoute
  '/_protected/oprasional/casbon/': typeof ProtectedOprasionalCasbonIndexRoute
  '/_protected/oprasional/oprasional/': typeof ProtectedOprasionalOprasionalIndexRoute
  '/_protected/oprasional/pembayaran/': typeof ProtectedOprasionalPembayaranIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/home'
    | '/login'
    | '/dashboard'
    | '/komersial/email'
    | '/keuangan/expense/$id'
    | '/komersial/penawaran/$id'
    | '/oprasional/casbon/$id'
    | '/oprasional/casbon/create'
    | '/oprasional/oprasional/$id'
    | '/oprasional/pembayaran/$id'
    | '/keuangan/expense/'
    | '/komersial/penawaran/'
    | '/oprasional/casbon/'
    | '/oprasional/oprasional/'
    | '/oprasional/pembayaran/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/home'
    | '/login'
    | '/dashboard'
    | '/komersial/email'
    | '/keuangan/expense/$id'
    | '/komersial/penawaran/$id'
    | '/oprasional/casbon/$id'
    | '/oprasional/casbon/create'
    | '/oprasional/oprasional/$id'
    | '/oprasional/pembayaran/$id'
    | '/keuangan/expense'
    | '/komersial/penawaran'
    | '/oprasional/casbon'
    | '/oprasional/oprasional'
    | '/oprasional/pembayaran'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/about'
    | '/home'
    | '/login'
    | '/_protected/dashboard'
    | '/_protected/komersial/email'
    | '/_protected/keuangan/expense/$id'
    | '/_protected/komersial/penawaran/$id'
    | '/_protected/oprasional/casbon/$id'
    | '/_protected/oprasional/casbon/create'
    | '/_protected/oprasional/oprasional/$id'
    | '/_protected/oprasional/pembayaran/$id'
    | '/_protected/keuangan/expense/'
    | '/_protected/komersial/penawaran/'
    | '/_protected/oprasional/casbon/'
    | '/_protected/oprasional/oprasional/'
    | '/_protected/oprasional/pembayaran/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/email': {
      id: '/_protected/komersial/email'
      path: '/komersial/email'
      fullPath: '/komersial/email'
      preLoaderRoute: typeof ProtectedKomersialEmailRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/pembayaran/': {
      id: '/_protected/oprasional/pembayaran/'
      path: '/oprasional/pembayaran'
      fullPath: '/oprasional/pembayaran/'
      preLoaderRoute: typeof ProtectedOprasionalPembayaranIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/oprasional/': {
      id: '/_protected/oprasional/oprasional/'
      path: '/oprasional/oprasional'
      fullPath: '/oprasional/oprasional/'
      preLoaderRoute: typeof ProtectedOprasionalOprasionalIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/casbon/': {
      id: '/_protected/oprasional/casbon/'
      path: '/oprasional/casbon'
      fullPath: '/oprasional/casbon/'
      preLoaderRoute: typeof ProtectedOprasionalCasbonIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/penawaran/': {
      id: '/_protected/komersial/penawaran/'
      path: '/komersial/penawaran'
      fullPath: '/komersial/penawaran/'
      preLoaderRoute: typeof ProtectedKomersialPenawaranIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/keuangan/expense/': {
      id: '/_protected/keuangan/expense/'
      path: '/keuangan/expense'
      fullPath: '/keuangan/expense/'
      preLoaderRoute: typeof ProtectedKeuanganExpenseIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/pembayaran/$id': {
      id: '/_protected/oprasional/pembayaran/$id'
      path: '/oprasional/pembayaran/$id'
      fullPath: '/oprasional/pembayaran/$id'
      preLoaderRoute: typeof ProtectedOprasionalPembayaranIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/oprasional/$id': {
      id: '/_protected/oprasional/oprasional/$id'
      path: '/oprasional/oprasional/$id'
      fullPath: '/oprasional/oprasional/$id'
      preLoaderRoute: typeof ProtectedOprasionalOprasionalIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/casbon/create': {
      id: '/_protected/oprasional/casbon/create'
      path: '/oprasional/casbon/create'
      fullPath: '/oprasional/casbon/create'
      preLoaderRoute: typeof ProtectedOprasionalCasbonCreateRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/oprasional/casbon/$id': {
      id: '/_protected/oprasional/casbon/$id'
      path: '/oprasional/casbon/$id'
      fullPath: '/oprasional/casbon/$id'
      preLoaderRoute: typeof ProtectedOprasionalCasbonIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/komersial/penawaran/$id': {
      id: '/_protected/komersial/penawaran/$id'
      path: '/komersial/penawaran/$id'
      fullPath: '/komersial/penawaran/$id'
      preLoaderRoute: typeof ProtectedKomersialPenawaranIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/keuangan/expense/$id': {
      id: '/_protected/keuangan/expense/$id'
      path: '/keuangan/expense/$id'
      fullPath: '/keuangan/expense/$id'
      preLoaderRoute: typeof ProtectedKeuanganExpenseIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedKomersialEmailRoute: typeof ProtectedKomersialEmailRoute
  ProtectedKeuanganExpenseIdRoute: typeof ProtectedKeuanganExpenseIdRoute
  ProtectedKomersialPenawaranIdRoute: typeof ProtectedKomersialPenawaranIdRoute
  ProtectedOprasionalCasbonIdRoute: typeof ProtectedOprasionalCasbonIdRoute
  ProtectedOprasionalCasbonCreateRoute: typeof ProtectedOprasionalCasbonCreateRoute
  ProtectedOprasionalOprasionalIdRoute: typeof ProtectedOprasionalOprasionalIdRoute
  ProtectedOprasionalPembayaranIdRoute: typeof ProtectedOprasionalPembayaranIdRoute
  ProtectedKeuanganExpenseIndexRoute: typeof ProtectedKeuanganExpenseIndexRoute
  ProtectedKomersialPenawaranIndexRoute: typeof ProtectedKomersialPenawaranIndexRoute
  ProtectedOprasionalCasbonIndexRoute: typeof ProtectedOprasionalCasbonIndexRoute
  ProtectedOprasionalOprasionalIndexRoute: typeof ProtectedOprasionalOprasionalIndexRoute
  ProtectedOprasionalPembayaranIndexRoute: typeof ProtectedOprasionalPembayaranIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedKomersialEmailRoute: ProtectedKomersialEmailRoute,
  ProtectedKeuanganExpenseIdRoute: ProtectedKeuanganExpenseIdRoute,
  ProtectedKomersialPenawaranIdRoute: ProtectedKomersialPenawaranIdRoute,
  ProtectedOprasionalCasbonIdRoute: ProtectedOprasionalCasbonIdRoute,
  ProtectedOprasionalCasbonCreateRoute: ProtectedOprasionalCasbonCreateRoute,
  ProtectedOprasionalOprasionalIdRoute: ProtectedOprasionalOprasionalIdRoute,
  ProtectedOprasionalPembayaranIdRoute: ProtectedOprasionalPembayaranIdRoute,
  ProtectedKeuanganExpenseIndexRoute: ProtectedKeuanganExpenseIndexRoute,
  ProtectedKomersialPenawaranIndexRoute: ProtectedKomersialPenawaranIndexRoute,
  ProtectedOprasionalCasbonIndexRoute: ProtectedOprasionalCasbonIndexRoute,
  ProtectedOprasionalOprasionalIndexRoute:
    ProtectedOprasionalOprasionalIndexRoute,
  ProtectedOprasionalPembayaranIndexRoute:
    ProtectedOprasionalPembayaranIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
